name: Build Alfred workflow and create release artifact

on: [push]

jobs:
  create-release-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Alfred workflow
        run: make all
      - name: Get version number
        id: workflow-version
        run: >-
          echo "::set-output name=WORKFLOW_VERSION::$(
            awk '/version/{getline; print}' info.plist |
            awk '/string/' |
            sed 's/[^0-9.]*//g'
          )"
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ steps.workflow-version.outputs.WORKFLOW_VERSION }}
          tag_name: ${{ steps.workflow-version.outputs.WORKFLOW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Alfred workflow
        id: upload-workflow
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./Timer.alfredworkflow
          asset_name: Timer.alfredworkflow
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
